name: ChatHead
version: '${project.version}'
main: com.chathead.ChatHead
api-version: '1.20'
commands:
  chathead:
    permission: chathead.admin
    permission-message: "ยง4You cannot use this command."
    usage: "ยงc/chathead <player-for-head> [<player-to-send>] (leave blank to send to yourself)"